version: '2'

services:
  isbpanel-frontend-movie:
    container_name: isbpanel-frontend-movie
    image: isbpanel-frontend-movie:0.2.4
    build: .
    volumes:
    - ./frontendmovie:/app/frontendmovie
    ports:
      - 3011:3011
    restart: always